
import math
import pyb


DRV8825_DIR_PIN = pyb.Pin.board.PC3
DRV8825_STEP_PIN = pyb.Pin.board.PA0
DRV8825_SLEEP_PIN = pyb.Pin.board.PA1
DRV8825_RESET_PIN = pyb.Pin.board.PA4
DRV8825_ENABLE_PIN = pyb.Pin.board.PB0
DRV8825_M0_PIN = pyb.Pin.board.PB6
DRV8825_M1_PIN = pyb.Pin.board.PA7
DRV8825_M2_PIN = pyb.Pin.board.PA6

FLYWHEEL_MOTOR_PWM_PIN = pyb.Pin.board.PB10
FLYWHEEL_MOTOR_PWM_PIN_TIMER_NUM = 2
FLYWHEEL_MOTOR_PWM_PIN_TIMER_CHANNEL = 3

FLYWHEEL_MOTOR_PWM_FREQUENCY = 50

FLYWHEEL_MOTOR_MAX_PWM = 10
FLYWHEEL_MOTOR_MIN_PWM = 5

ADC_MAX_INTEGER = 4095

TIM4_FREQ = 80000000
TIM4_MAX = 65535
TIM4_PRESCALER = 9

TIM4_SCALED_FREQ = TIM4_FREQ / (TIM4_PRESCALER+1)
TIM4_SCALED_TICK_PERIOD_NS = int((1/TIM4_SCALED_FREQ)*1e9)

STEPPER_OVERHEAD_EST_US = 0

ONBOARD_BUTTON_PIN = pyb.Pin.board.PC13


DRV8825_STEP_PIN_TIMER_NUM = 2
DRV8825_STEP_PIN_TIMER_CHAN = 1

STEP_MOTOR_STEP_PER_REV = 200
MICROSTEPS = 1

PULLEY_RATIO = 9.5

MICROSTEPS_PER_REV = STEP_MOTOR_STEP_PER_REV*MICROSTEPS
STEP_MOTOR_ALPHA = (2*math.pi)/ MICROSTEPS_PER_REV #motor step angle α

class AccelStates():
    error = -1
    accelerating = 1
    running = 2
    decelerating = 3
    stopped = 4

M1_STEP_TASK_PRIORITY = 99

