
import math
import pyb


DRV8825_DIR_PIN = pyb.Pin.board.PC3
DRV8825_STEP_PIN = pyb.Pin.board.PA0
DRV8825_SLEEP_PIN = pyb.Pin.board.PA1
DRV8825_RESET_PIN = pyb.Pin.board.PA4
DRV8825_ENABLE_PIN = pyb.Pin.board.PB0
DRV8825_M0_PIN = pyb.Pin.board.PB6
DRV8825_M1_PIN = pyb.Pin.board.PA7
DRV8825_M2_PIN = pyb.Pin.board.PA6

STEPPER_I2C_ADDR = 0x69

FLYWHEEL_MOTOR_PWM_PIN = pyb.Pin.board.PB10
FLYWHEEL_MOTOR_PWM_PIN_TIMER_NUM = 2
FLYWHEEL_MOTOR_PWM_PIN_TIMER_CHANNEL = 3

FLYWHEEL_MOTOR_PWM_FREQUENCY = 50

FLYWHEEL_MOTOR_MAX_PWM = 10
FLYWHEEL_MOTOR_MIN_PWM = 5

ADC_MAX_INTEGER = 4095

STEPPER_OVERHEAD_EST_US = 0

ONBOARD_BUTTON_PIN = pyb.Pin.board.PC13

STEP_MOTOR_STEP_PER_REV = 200
MICROSTEPS = 1

CAMERA_TARGET_DIST_IN = 200#192
SHOOTER_TARGET_DIST_IN = 300#192-60-30
CAM_FOV_DEG = 55
CAM_X_PIXELS = 32

CAM_TARGET_ANGLE_OFFSET = 0

PULLEY_RATIO = 9.5

MICROSTEPS_PER_REV = STEP_MOTOR_STEP_PER_REV*MICROSTEPS

class AccelStates():
    error = -1
    accelerating = 1
    running = 2
    decelerating = 3
    stopped = 4

M1_STEP_TASK_PRIORITY = 99



##Servo

SERVO_PWM_PIN = pyb.Pin.board.PA9
SERVO_PWM_PIN_TIMER_NUM = 1
SERVO_PWM_PIN_TIMER_CHANNEL = 2

SERVO_PWM_FREQUENCY = 50

# constants to set servo freq to 50hz w/ tick int of 1us
SERVO_TIMER_ARR = 19999
SERVO_TIMER_PS = 79

SERVO_MAX_PWM_US = 2600
SERVO_MIN_PWM_US = 600
SERVO_ANGLE_RANGE = 180

